version: "3.7"

services:
  loki:
    image: grafana/loki:latest
    container_name: ${PROJECT_NAME}_loki
    expose:
      - "3100"
      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${PROJECT_NAME}_loki.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_loki.rule=Host(`${DOMAINE_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}_loki.rule=Host(`${DOMAINE_NAME}`) || Host(`www.${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_loki-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.${PROJECT_NAME}_loki-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}/$${1}"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}_loki-redirectregex"


networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}