version: '3.4'

volumes:
  web_data:
    name: ${CONTAINER_NAME}
  db_data:
    name: ${CONTAINER_NAME}_db

services:

  odoo:
    container_name: ${CONTAINER_NAME}
    image: odoo:14
    volumes:
      - web_data:/var/lib/odoo/
      - "./modules:/mnt/extra-addons:rw"
      - "./odoo.conf:/etc/odoo/odoo.conf:rw"

    environment:
    - USER=${POSTGRES_USER}
    - PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${CONTAINER_NAME}.tls=true"

      # Support of www domaine with and redirect to without www
      - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAINE_NAME}`) || Host(`www.${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.${CONTAINER_NAME}-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.${CONTAINER_NAME}-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}/$${1}"
      - "traefik.http.routers.${CONTAINER_NAME}.middlewares=${CONTAINER_NAME}-redirectregex"



  db:
    container_name: ${CONTAINER_NAME}_db
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=postgres


  adminer:
    image: adminer
    container_name: ${CONTAINER_NAME}_adminer
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME}_adminer.entrypoints=websecure"
      - "traefik.http.routers.${CONTAINER_NAME}_adminer.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME}_adminer.rule=Host(`${DOMAINE_NAME}`) && (PathPrefix(`/bd`))"
      - "traefik.http.middlewares.${CONTAINER_NAME}_adminer-auth.basicauth.usersfile=/etc/traefik/passwd/user.password"
      - "traefik.http.routers.${CONTAINER_NAME}_adminer.middlewares=${CONTAINER_NAME}_adminer-auth"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=${CONTAINER_NAME}_db
      - ADMINER_DESIGN=pappu687

networks:
  default:
    external:
      name: $DEFAULT_NETWORK