version: "3.7"

volumes:
    uploads:
      name: ${DOMAINE_NAME}_bookstack_uploads
    storage-uploads:
      name: ${DOMAINE_NAME}_bookstack_storage_uploads
    mysql-data:
      name: ${DOMAINE_NAME}_bookstack_mysql

services:
  bookstack:
    image: linuxserver/bookstack
    container_name: ${DOMAINE_NAME}_bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=
      - DB_HOST=${DOMAINE_NAME}_bookstack_db
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.bookstack.entrypoints=web"
      - "traefik.http.routers.bookstack.rule=Host(`${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.bookstack-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.bookstack-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}/$${1}"
      - "traefik.http.routers.bookstack.middlewares=bookstack-redirectregex"

    volumes:
      - ./etc:/config
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/storage/uploads

    restart: unless-stopped
    

  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: ${DOMAINE_NAME}_bookstack_db
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}