version: '3.7'

volumes:
    grafana_data:
      name: ${PROJECT_NAME}_grafana


services:

  grafana:
    image: grafana/grafana:7.3.6
    container_name: ${PROJECT_NAME}_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./etc/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-Success2021}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${PROJECT_NAME}_grafana.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_grafana.rule=Host(`${DOMAINE_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}_grafana.rule=Host(`${DOMAINE_NAME}`) || Host(`www.${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_grafana-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.${PROJECT_NAME}_grafana-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}/$${1}"
      - "traefik.http.routers.${PROJECT_NAME}_grafana.middlewares=${PROJECT_NAME}_grafana-redirectregex"


      
networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}