
version: '3.7'

volumes:
    docker-registry_data:
      name: ${PROJECT_NAME}_docker-registry

services:
  registry:
    image: registry:2
    container_name: ${PROJECT_NAME}_docker-registry
    expose:
      - 5000
    volumes:
      #- ./config/config.yml:/etc/docker/registry/config.yml:ro
      - docker-registry_data:/var/lib/registry:rw

    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${PROJECT_NAME}_docker-registry.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_docker-registry.rule=Host(`${DOMAINE_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}_docker-registry.rule=Host(`${DOMAINE_NAME}`) || Host(`www.${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_docker-registry-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.${PROJECT_NAME}_docker-registry-auth.basicauth.usersfile=/password"
      - "traefik.http.middlewares.${PROJECT_NAME}_docker-registry-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}/$${1}"
      - "traefik.http.routers.${PROJECT_NAME}_docker-registry.middlewares=${PROJECT_NAME}_docker-registry-redirectregex,${PROJECT_NAME}_docker-registry-auth"


networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}