version: '3.4'

volumes:
  data:
    name: ${CONTAINER_NAME}

services:

  app:
    image: vaultwarden/sha256:fe2a236b792fb2304ef50f86f1c25076ac5b2748e1b776fce260ad12ad29188d
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - data:/data

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${CONTAINER_NAME}.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME}.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAINE_NAME}`)"

    environment:
      - DOMAIN=https://${DOMAINE_NAME}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED} # Required to use websockets
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}   # set to false to disable signups
networks:
  default:
    external:
      name: $DEFAULT_NETWORK
