version: '3.7'

services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    container_name: ${PROJECT_NAME}_cadvisor
    volumes:
      - /:/rootfs:ro,rslave
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
    - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${PROJECT_NAME}_cadvisor.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_cadvisor.rule=Host(`${DOMAINE_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}_cadvisor.rule=Host(`${DOMAINE_NAME}`) || Host(`www.${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_cadvisor-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.${PROJECT_NAME}_cadvisor-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}/$${1}"
      - "traefik.http.routers.${PROJECT_NAME}_cadvisor.middlewares=${PROJECT_NAME}_cadvisor-redirectregex"


networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}