version: "3.7"


services:

  promtail:
    image: grafana/promtail:master
    container_name: ${PROJECT_NAME}_promtail

    volumes:
      - ./etc/loki-promtail.yml:/etc/promtail/docker-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml

    restart: unless-stopped
    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.${PROJECT_NAME}_promtail.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_promtail.rule=Host(`${DOMAINE_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}promtail.rule=Host(`${DOMAINE_NAME}`) || Host(`www.${DOMAINE_NAME}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_promtail-redirectregex.redirectregex.regex=^https://www.${DOMAINE_NAME}/(.*)"
      - "traefik.http.middlewares.${PROJECT_NAME}_promtail-auth.basicauth.usersfile=/password"
      - "traefik.http.middlewares.${PROJECT_NAME}_promtail-redirectregex.redirectregex.replacement=https://${DOMAINE_NAME}$${1}"
      - "traefik.http.routers.docker_registry.middlewares=${PROJECT_NAME}_promtail-redirectregex,${PROJECT_NAME}_promtail-auth"
    logging:
      driver: loki
      options:
        loki-url: "http://loki_visi_loki:3100/loki/api/v1/push"

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}