version: "3.7"

services:
  traefik:
    image: traefik:2.4.8
    container_name: traefik
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./etc/traefik.yml:/traefik.yml:ro"
      - "./etc/ssl:/etc/traefik/ssl:ro"
      - "./etc/passwd:/etc/traefik/passwd:ro"
      - "./acme:/etc/traefik/acme"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DEFAULT_NETWORK}"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - traefik.http.routers.traefik.tls.certresolver=letsEncrypt


      - "traefik.http.routers.traefik.rule=Host(`${DOMAINE_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.service=api@internal"


      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/etc/traefik/passwd/user.password"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}